spring:
  profiles:
    active: dev #激活开发环境配置
---
server:
  port: 4001 #端口号
spring:
  profiles: dev #生产环境
  applications:
    name: microservice-config-dev
---
server:
  port: 4002 #端口号
spring:
  profiles: pord #生产环境
  applications:
    name: microservice-config-prod
